import { Analytics } from '@vercel/analytics/react'
import type { Metadata } from 'next'
import './globals.css'
import Header from './components/layout/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="nb">
      <body>
        <Header title='Ole Jørgen' />
        {children}
        <Analytics />
      </body>
    </html>
  )
}
