import Head from 'next/head'
import Header from '../components/header/header'
import { work, education, volunteering, projects, languages, links } from '../lib/cv';
import Job from '../components/cv/job/job';
import School from '../components/cv/school/school';
import Project from '../components/cv/project/project';

import styles from '../styles/pages/index.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className={styles.cv}>
          <h2>Projects</h2>
          {projects.map((project) => (
            <Project name={project.name} description={project.description} startDate={project.startDate} endDate={project.endDate} url={project.url} highlights={project.highlights} />
          ))}
          <h2>Work</h2>
          {work.map((job) => (
            <Job business={job.business} position={job.position} startDate={job.startDate} endDate={job.endDate} summary={job.summary} highlights={job.highlights} />
          ))}
          <h2>Education</h2>
          {education.map((school) => (
            <School institution={school.institution} area={school.area} startDate={school.startDate} endDate={school.endDate} summary={school.summary} courses={school.courses} />
          ))}
          <h2>Volunteering</h2>
          {volunteering.map((volunteer) => (
            <Job business={volunteer.organization} position={volunteer.position} startDate={volunteer.startDate} endDate={volunteer.endDate} summary={volunteer.summary} highlights={volunteer.highlights} />
          ))}
          <aside>
            <h2>Languages</h2>
            <ul>
              {languages.map((language) => (
                <li>{language.language} - {language.fluency}</li>
              ))}
            </ul>
            <h2>Links</h2>
            <ul>
              {links.map((link) => (
                <li><a href={link.url}>{link.name}</a></li>
              ))}
            </ul>
          </aside>
        </div>

      </main>
    </div>
  )
}
