import type { Repository } from './repository.model';

export const mockRepositories: Repository[] = [
  {
    name: 'olejorgen.no',
    description: 'Noe noe',
    html_url: 'https://www.github.com/olejorgenbakken/olejorgen.no',
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    topics: ['nextjs', 'typescript'],
    language: 'TypeScript',
  },
  {
    name: 'olejorgen.no',
    description: 'Noe noe',
    html_url: 'https://www.github.com/olejorgenbakken/olejorgen.no',
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    topics: ['nextjs', 'typescript'],
    language: 'TypeScript',
  },
  {
    name: 'olejorgen.no',
    description: 'Noe noe',
    html_url: 'https://www.github.com/olejorgenbakken/olejorgen.no',
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    topics: ['nextjs', 'typescript'],
    language: 'TypeScript',
  },
  {
    name: 'olejorgen.no',
    description: 'Noe noe',
    html_url: 'https://www.github.com/olejorgenbakken/olejorgen.no',
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    topics: ['nextjs', 'typescript'],
    language: 'TypeScript',
  },
  {
    name: 'olejorgen.no',
    description: 'Noe noe',
    html_url: 'https://www.github.com/olejorgenbakken/olejorgen.no',
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    topics: ['nextjs', 'typescript'],
    language: 'TypeScript',
  },
  {
    name: 'olejorgen.no',
    description: 'Noe noe',
    html_url: 'https://www.github.com/olejorgenbakken/olejorgen.no',
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    topics: ['nextjs', 'typescript'],
    language: 'TypeScript',
  },
];
